"""create projects table

Revision ID: 0e634baacfda
Revises: 80223d837270
Create Date: 2024-11-29 13:48:35.152891

"""
from typing import Sequence, Union
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '0e634baacfda'
down_revision: Union[str, None] = '80223d837270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description_activity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('customer_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_project'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activitys', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'activitys', type_='foreignkey')
    op.create_foreign_key(None, 'activitys', 'projects', ['project_id'], ['id'])
    op.drop_column('activitys', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('customer_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'activitys', type_='foreignkey')
    op.create_foreign_key(None, 'activitys', 'users', ['customer_id'], ['id'])
    op.drop_column('activitys', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
